# Generated by Django 5.1.2 on 2024-10-19 06:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('assistant', '0002_chat_message_delete_userimage'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='message',
            name='role',
        ),
    ]
