# Generated by Django 5.1.2 on 2024-10-19 21:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assistant', '0004_message_role'),
    ]

    operations = [
        migrations.AddField(
            model_name='chat',
            name='is_cancer_related',
            field=models.BooleanField(default=None, null=True),
        ),
    ]
